services:
  sendspin-relay:
    image: ghcr.io/woliver99/sendspin-relay:latest
    container_name: sendspin-relay
    ports:
      - "8000:8000"
    environment:
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=8000
      # - TRUSTED_PROXY_IP=10.10.10.0/24
    restart: always
